changes based on feedback

diff --git a/.github/workflows/backend-cd.yaml b/.github/workflows/backend-cd.yaml
--- a/.github/workflows/backend-cd.yaml
+++ b/.github/workflows/backend-cd.yaml
@@ -83,80 +83,11 @@ jobs:
           pipenv install
           pipenv run test
 
-  create-infra:
-    name: create-infra #This job would create the required infrastructure using terraform
-    needs: 
-      - backend-cd-test
-      - backend-cd-lint
-    runs-on: ubuntu-latest
-
-    steps:
-    - name: Checkout code
-      uses: actions/checkout@v4
-
-    - name: Set up AWS CLI
-      uses: aws-actions/configure-aws-credentials@v1
-      with:
-        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
-        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-        aws-region: ${{ vars.AWS_REGION }}
-
-    - name: Set up Terraform
-      uses: hashicorp/setup-terraform@v1
-      with:
-        terraform_version: 1.3.9
-
-    - name: Terraform Init
-      run: cd setup/terraform && terraform init
-
-    - name: Terraform Validate
-      run: cd setup/terraform && terraform validate 
-
-    - name: Terraform Plan
-      run: cd setup/terraform && terraform plan -var "aws_default_region=${{ vars.AWS_REGION }}" -var "aws_account_id=${{ vars.AWS_ACCOUNT_ID }}" -var "github_pat=${{ secrets.TOKEN_GITHUB }}"
-      continue-on-error: true
-
-    - name: Terraform Apply
-      run: |
-        cd setup/terraform && terraform apply -auto-approve -var "aws_default_region=${{ vars.AWS_REGION }}" -var "aws_account_id=${{ vars.AWS_ACCOUNT_ID }}" -var "github_pat=${{ secrets.TOKEN_GITHUB }}"
-
-    - name: Terraform Destroy on Failure
-      if: failure()
-      run: terraform destroy -auto-approve -refresh=false -var "aws_default_region=${{ vars.AWS_REGION }}" -var "aws_account_id=${{ vars.AWS_ACCOUNT_ID }}" -var "github_pat=${{ secrets.TOKEN_GITHUB }}"
-      working-directory: ./setup/terraform
-
-    - name: Upload Terraform state file
-      if: success()
-      uses: actions/upload-artifact@v3
-      with:
-        name: terraform-state
-        path: setup/terraform/terraform.tfstate
-
-    - name: Check EKS Cluster Status
-      run: |
-        aws eks describe-cluster --name ${{vars.CLUSTER_NAME}} --region ${{vars.AWS_REGION}} | jq -e '.cluster.status == "ACTIVE"' > /dev/null
-      continue-on-error: false
-
-  # wait_for_eks:
-  #   runs-on: ubuntu-latest
-  #   needs: create-infra
-  #   steps:
-  #     - name: Set up AWS CLI
-  #       uses: aws-actions/configure-aws-credentials@v1
-  #       with:
-  #         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
-  #         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-  #         aws-region: ${{ vars.AWS_REGION }}
-
-  #     - name: Check EKS Cluster Status
-  #       run: |
-  #         aws eks describe-cluster --name ${{vars.CLUSTER_NAME}} --region ${{vars.AWS_REGION}} | jq -e '.cluster.status == "ACTIVE"' > /dev/null
-  #       continue-on-error: false
-
   backend-cd-build:      
     name: backend-cd-build
     needs: 
-    - create-infra
+    - backend-cd-test
+    - backend-cd-lint
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4
@@ -191,101 +122,24 @@ jobs:
           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           aws-region: ${{ vars.AWS_REGION }}
 
-      - name: Trigger CodeBuild
+      - name: Login to ECR
+        id: login-ecr
+        uses: aws-actions/amazon-ecr-login
+
+      - name: Build, tag, and push docker image to Amazon ECR
         env:
-          PROJECT_NAME: udacity
+          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
+          IMAGE_NAME: backend
         run: |
-          aws codebuild start-build --project-name $PROJECT_NAME --environment-variables-override name=AWS_DEFAULT_REGION,value=${{vars.AWS_REGION}} name=AWS_ACCOUNT_ID,value=${{vars.AWS_ACCOUNT_ID}} name=APP_NAME,value=backend
+          echo Building docker image for backend ..
+          docker build -t $REGISTRY/$IMAGE_NAME:${GITHUB_SHA::7} starter/backend/.
+          echo Pushing the backend docker image to ECR repo
+          docker push $REGISTRY/$IMAGE_NAME:${GITHUB_SHA::7}
       
-      - name: Fetch and wait for CodeBuild success
-        env:
-          PROJECT_NAME: "udacity"
-        run: |
-          # Fetch the latest build ID
-          build_id=$(aws codebuild list-builds-for-project --project-name $PROJECT_NAME --max-items 1 --query 'ids[0]' --output text)
-
-          # Check if build ID was fetched successfully
-          if [ -z "$build_id" ]; then
-            echo "No build ID found for the project."
-            exit 1
-          fi
-
-          echo "Latest build ID: $build_id"
-
-          # Loop to wait for build completion
-          while true; do
-            build_status=$(aws codebuild batch-get-builds --ids "$build_id" --query 'builds[0].buildStatus' --output text)
-
-            if [ "$build_status" == "SUCCEEDED" ]; then
-              echo "Build succeeded!"
-              break
-            elif [ "$build_status" == "FAILED" ]; then
-              echo "Build failed."
-              exit 1
-            elif [ "$build_status" == "IN_PROGRESS" ]; then
-              echo "Build still in progress, checking again in 30 seconds..."
-              sleep 30
-            else
-              echo "Build encountered an unexpected status: $build_status"
-              exit 1
-            fi
-          done
-        continue-on-error: false
-
-  # wait_for_codebuild:
-  #   runs-on: ubuntu-latest
-  #   needs: backend-cd-build
-  #   steps:
-  #     - name: Set up AWS CLI
-  #       uses: aws-actions/configure-aws-credentials@v1
-  #       with:
-  #         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
-  #         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-  #         aws-region: ${{ vars.AWS_REGION }}
-
-  #     - name: Fetch and wait for CodeBuild success
-  #       env:
-  #         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
-  #         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-  #         AWS_DEFAULT_REGION: ${{ vars.AWS_REGION }}
-  #         PROJECT_NAME: "udacity"
-  #       run: |
-  #         # Fetch the latest build ID
-  #         build_id=$(aws codebuild list-builds-for-project --project-name $PROJECT_NAME --max-items 1 --query 'ids[0]' --output text)
-
-  #         # Check if build ID was fetched successfully
-  #         if [ -z "$build_id" ]; then
-  #           echo "No build ID found for the project."
-  #           exit 1
-  #         fi
-
-  #         echo "Latest build ID: $build_id"
-
-  #         # Loop to wait for build completion
-  #         while true; do
-  #           build_status=$(aws codebuild batch-get-builds --ids "$build_id" --query 'builds[0].buildStatus' --output text)
-
-  #           if [ "$build_status" == "SUCCEEDED" ]; then
-  #             echo "Build succeeded!"
-  #             break
-  #           elif [ "$build_status" == "FAILED" ]; then
-  #             echo "Build failed."
-  #             exit 1
-  #           elif [ "$build_status" == "IN_PROGRESS" ]; then
-  #             echo "Build still in progress, checking again in 30 seconds..."
-  #             sleep 30
-  #           else
-  #             echo "Build encountered an unexpected status: $build_status"
-  #             exit 1
-  #           fi
-  #         done
-  #       continue-on-error: false
-
   backend-cd-deploy:
     name: backend-cd-deploy
     runs-on: ubuntu-latest
     needs: 
-      - create-infra
       - backend-cd-build
     steps:
       - name: Checkout Code
@@ -303,43 +157,45 @@ jobs:
           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           aws-region: ${{ vars.AWS_REGION }}
 
+      - name: Login to ECR
+        id: login-ecr
+        uses: aws-actions/amazon-ecr-login
+
       - name: Generate Kubeconfig
         run: |
-          CLUSTER_NAME=$(aws eks list-clusters --region ${{ vars.AWS_REGION }} --query "clusters[0]" --output text)
-          echo "Cluster Name: $CLUSTER_NAME"
-          aws eks update-kubeconfig --region ${{ vars.AWS_REGION }} --name $CLUSTER_NAME
+          aws eks update-kubeconfig --region ${{ vars.AWS_REGION }} --name ${{vars.CLUSTER_NAME}}
 
       - name: Setup Kustomize
         uses: imranismail/setup-kustomize@v2
 
       - name: Deploy backend App
+        env:
+          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
+          IMAGE_NAME: backend
         run: |
           cd starter/backend/k8s
-          aws ecr describe-repositories --repository-names backend --query 'repositories[*].[repositoryUri]' --output text
-          BACKEND_ECR=$(aws ecr describe-repositories --repository-names backend --query 'repositories[*].[repositoryUri]' --output text)
-          echo $BACKEND_ECR
-          kustomize edit set image backend=$BACKEND_ECR:${{ github.sha }}
+          kustomize edit set image backend=$REGISTRY/$IMAGE_NAME:${GITHUB_SHA::7}
           kustomize build | kubectl apply -f -
           kubectl rollout status deployment/backend
-          if [ $? -eq 0 ]; then
-            echo "Rollout successful. Fetching the external IP or DNS name..."
+          # if [ $? -eq 0 ]; then
+          #   echo "Rollout successful. Fetching the external IP or DNS name..."
   
-            # Get the external IP or DNS name of the service
-            EXTERNAL_IP=$(kubectl get svc backend -o json | jq -r '.status.loadBalancer.ingress[0].hostname')
+          #   # Get the external IP or DNS name of the service
+          #   EXTERNAL_IP=$(kubectl get svc backend -o json | jq -r '.status.loadBalancer.ingress[0].hostname')
             
-            # Check if the EXTERNAL_IP is not empty
-            echo "Check if the EXTERNAL_IP is not empty"
-            if [ -n "$EXTERNAL_IP" ]; then
-              echo "External IP or DNS name: $EXTERNAL_IP"
-              echo "EXTERNALIP=$EXTERNAL_IP" > externalip.txt
-              aws s3api create-bucket --bucket ${{ vars.AWS_ACCOUNT_ID }} --region ${{vars.AWS_REGION}} --create-bucket-configuration LocationConstraint=${{vars.AWS_REGION}}
-              aws s3 cp externalip.txt s3://${{ vars.AWS_ACCOUNT_ID }}/
-            else
-              echo "External IP or DNS name not available yet."
-            fi
-          else
-            echo "Rollout failed."
-          fi
+          #   # Check if the EXTERNAL_IP is not empty
+          #   echo "Check if the EXTERNAL_IP is not empty"
+          #   if [ -n "$EXTERNAL_IP" ]; then
+          #     echo "External IP or DNS name: $EXTERNAL_IP"
+          #     echo "EXTERNALIP=$EXTERNAL_IP" > externalip.txt
+          #     aws s3api create-bucket --bucket ${{ vars.AWS_ACCOUNT_ID }} --region ${{vars.AWS_REGION}} --create-bucket-configuration LocationConstraint=${{vars.AWS_REGION}}
+          #     aws s3 cp externalip.txt s3://${{ vars.AWS_ACCOUNT_ID }}/
+          #   else
+          #     echo "External IP or DNS name not available yet."
+          #   fi
+          # else
+          #   echo "Rollout failed."
+          # fi
 
         
  
